### PR TITLE
Dataset info widget

### PR DESCRIPTION
**Pull request by tplatt77**
A dataset info widget is added as a new tab for the info/settings widget on IMFViewer. It has origin, extent, and bounds info for the selected dataset.

### CODE REVIEW

**Review by joeykleingers — CHANGES_REQUESTED** [review]
* Remove the edge padding around the content in both the Settings tab and the Information tab.

* Make sure that the Settings tab is displayed first when the application launches.  Right now Information is displayed first.

* Add a vertical spacer at the bottom of the VSDatasetInfoWidget, because otherwise it stretches really far vertically and looks super odd.

* The "Origin" bold label in the VSDatasetInfoWidget should be the same font size as the other Extents and Bounds bold labels.

* Add the dimension count in parentheses next to each extent, and add the delta in parentheses next to each bound.  Take a look at how Paraview does it and do it the same way.

* Add Spacing as another bold label and show the spacing of the image.

**Review by joeykleingers — CHANGES_REQUESTED** [review]
Looks good, although a few more changes are needed:

* The information tab should be cleared when there are no selections (putting N/A for each item or whatever you do when the application first launches works)

* The extents section should have each maximum decreased by 1.  If any of X, Y, or Z have a max - min that is <= 0, hide that coordinate.  Example:

X: 0 to 192
Y: 0 to 78
Z: 1 to 1

The above values would display in the Information pane like this:

X Extent: 0 to 191 (dimension: 192)
Y Extent: 0 to 77 (dimension: 78)

Z Extent is hidden because 1 - 1 = 0 (in other words, this is a 2D image).

**Comment by tplatt77** [comment]
Are we wanting to do this differently than Paraview? https://gitlab.kitware.com/paraview/paraview/blob/472ed9ed8f5174e24d29ac3abc8ca481394f4823/Qt/Components/pqProxyInformationWidget.cxx (Lines 351 through 370). 
They performed calculations the same way I did. 
extents_calc_Paraview

**Comment by joeykleingers** [comment]
We are currently getting the information we need from the VTK dataset, when instead we should be getting it from the geometry that is inside the wrapped data container in our VSSIMPLDataContainerFilter instance.  There's already a method called getInfoString in the IGeometry classes that already formats the string and everything.  I created a getInfoString pure virtual method in the VSAbstractFilter and VSAbstractDataFilter superclasses and then implemented the getInfoString method in each filter subclass.  Then inside VSSIMPLDataContainerFilter's version of the method, I returned the info string from the geometry in the wrapped data container.  The other VTK filters have a blank getInfoString method.

**Comment by joeykleingers** [comment]
I think we should probably add some basic information for all the other filters (Crop, Mask, etc.), but I'm not sure what information we should include.

**Review by joeykleingers — APPROVED** [review]

**Pull request merged**
